version: '3.9'
name: portainer
services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent
    ports:
      - "9001:9001" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s